[package]
name = "panscape"
version = "0.4.0"
edition = "2021"
readme = "README.md"
license = "MIT"
authors = ["Gaurav Sablok"]
description = "panscape for pangenomics"
homepage = "https://codeberg.org/gsablok/panscape"
repository = "https://codeberg.org/gsablok/panscape"
keywords = ["bioinformatics","genomics"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
charts = "0.3.0"
clap = { version = "=4.5.4", features = ["derive"] }
cmd_lib = "1.9.5"
figlet-rs = "0.1.5"
indexmap = "=2.2.6"
petgraph = "0.6"
rayon = "=1.10.0"
rayon-core = "=1.12.1"
regex = "1.11.1"
rusqlite = { version = "=0.31.0", features = ["bundled"] }
rustc-hash = "1.1"
tabled = "0.18.0"
textwrap = "0.16.1"
smawk = "=0.3.1"
